import {teachingPlanSchema} from '../schemas.js';
import {validateTeachingPlan} from './validate.js';
import type {TeachingPlanV2,VisualArchetype} from '../types.js';
import type {JsonModel} from './model-adapter.js';
export interface TeachingInput {prompt:string;sourceText?:string;sourceId?:string;maxScenes?:number;allowedArchetypes:VisualArchetype[]}
export async function planTeaching(input:TeachingInput,model:JsonModel):Promise<TeachingPlanV2>{
 if(!input.prompt.trim()||input.prompt.length>4000||(input.sourceText?.length??0)>32000)throw new Error('V2 prompt/source bounds exceeded');
 const maxScenes=input.maxScenes??1;if(!Number.isInteger(maxScenes)||maxScenes<1||maxScenes>8)throw new Error('V2 scene limit must be 1–8');
 return await model.generate('teaching',`Plan a coherent teaching arc and semantic beats, not a node/edge diagram. A scene keeps one central mental model on one board. Explicitly identify centralConceptId: the whole system being taught, not whichever subpart receives the most relations. Each beat teaches one conceptual change. Use at most ${maxScenes} scenes, 4–7 short beats per scene, approximately 12–20 words per beat. The requiredConceptIds inventory contains independently represented entities/materials. Subparts of the central system are semantic anchors ON THE SYSTEM, not separate requiredConceptIds or relation target concepts, unless their internal structure is the subject of this scene. For example, an input that enters roots targets the whole plant concept with targetAnchor roots; leaf input targets the plant with targetAnchor leaf.top or leaf.right. Keep four to six required concepts for an input-focused scene. Do not add a separate product object merely because the summary mentions food; a product object is needed only for a visual transformation scene. For an input-to-system relation, specify the real targetAnchor (roots, leaf.top, input, etc.). Introduce a central system before its inputs. All required concepts must appear in introduce/reinforce/transform. Every required relation must appear in relationFocus. Explicitly cover all critical requirementIds. The requirementIds list must include IDs from BOTH requiredClaims AND requiredMechanisms. Before returning, check every critical claim and mechanism ID occurs in at least one beat; especially include the overall mechanism ID in the combine/restate beat. Do not choose shapes or coordinates. Narration drafts must explain mechanisms naturally, not read labels. Use only the supplied allowed archetypes. If sourceText is supplied, quote exact source spans with its sourceId and reference them on each critical beat. If absent, evidenceRefs arrays stay empty; do not invent sources.`,input,teachingPlanSchema,value=>{
  const {plan}=validateTeachingPlan(value);if(plan.scenes.length>maxScenes)throw new Error('Too many scenes');
  for(const s of plan.scenes)if(s.candidateArchetypes.some(a=>!input.allowedArchetypes.includes(a)))throw new Error('Unavailable archetype');
  if(input.sourceText){for(const e of plan.evidenceRefs)if(e.sourceId!==(input.sourceId??'source')||!input.sourceText.includes(e.quote))throw new Error(`Fabricated evidence: ${e.id}`);if(!plan.evidenceRefs.length)throw new Error('Source-grounded plan requires evidence');}else if(plan.evidenceRefs.length)throw new Error('Prompt-only plan cannot invent evidence');
  return plan;
 }) as TeachingPlanV2;
}
