type JobRow={id:string;status:string;title?:string;targetMinutes?:number;actualMinutes?:number;costPerMinuteUsd?:number;createdAt:number;sceneCount:number;totalScenes?:number;availableMs:number;timingMode?:string;captionMode?:string;usage?:{costUsd?:number;calls?:number;model?:string};stageMs?:Record<string,number>;fallbackCount?:number;degradedStages?:Array<{stage:string;reason:string}>;error?:string};
type Audit={artifacts:Record<string,{present:boolean;bytes?:number;redacted?:boolean;value?:unknown}>;jobId:string;sourceContentIncluded:boolean};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const jobsEl=$<HTMLUListElement>('jobs'),detail=$<HTMLElement>('detail');
const formatTime=(ms:number|undefined)=>Number.isFinite(ms)?`${(Number(ms)/1000).toFixed(1)}s`:'—';
const formatDate=(ms:number)=>new Date(ms).toLocaleString();
let selected:string|undefined;
async function get<T>(path:string):Promise<T>{const res=await fetch(path,{cache:'no-store'});const value=await res.json();if(!res.ok)throw new Error(value.error||'Request failed');return value as T;}
function renderJobs(rows:JobRow[]){jobsEl.replaceChildren(...(rows.length?rows.map(row=>{const li=document.createElement('li');if(row.id===selected)li.className='active';const degradation=(row.fallbackCount||0)+(row.degradedStages?.length||0);li.innerHTML=`<strong>${escapeHtml(row.title||'Untitled lesson')}</strong><small>${row.id.slice(0,8)} · ${row.status} · ${row.targetMinutes||'?'} min · ${row.sceneCount}/${row.totalScenes||'?'} scenes${degradation?` · ${degradation} degradation(s)`:''}<br>${formatDate(row.createdAt)}</small>`;li.onclick=()=>{selected=row.id;void loadAudit(row.id);renderJobs(rows)};return li;}):[Object.assign(document.createElement('li'),{className:'empty',textContent:'No jobs have been generated yet.'})]));}
async function loadJobs(){try{const data=await get<{jobs:JobRow[]}>('/api/admin/jobs?limit=100');renderJobs(data.jobs);}catch(error){jobsEl.innerHTML=`<li class="empty">${escapeHtml(String(error))}</li>`;}}
async function loadAudit(id:string){detail.innerHTML='<div class="empty">Loading audit artifacts…</div>';try{const audit=await get<Audit>(`/api/jobs/${id}/audit`);renderAudit(audit);}catch(error){detail.innerHTML=`<div class="empty">${escapeHtml(String(error))}</div>`;}}
function renderAudit(audit:Audit){const job=(audit.artifacts['job.json']?.value||{}) as JobRow&{stageMs?:Record<string,number>;usage?:JobRow['usage']};const artifacts=Object.entries(audit.artifacts).sort(([a],[b])=>a.localeCompare(b));const stage=Object.entries(job.stageMs||{}).map(([name,ms])=>`${name}: ${formatTime(ms)}`).join(' · ')||'No stage timing recorded';const cost=job.usage?.costUsd===undefined?'—':`$${job.usage.costUsd.toFixed(4)}`;const costPerMinute=job.costPerMinuteUsd===undefined?'—':`$${job.costPerMinuteUsd.toFixed(4)}/min`;detail.innerHTML=`<h2 class="audit-title">${escapeHtml(String(job.title||audit.jobId))}</h2><p class="muted"><span class="badge">${escapeHtml(String(job.status||'unknown'))}</span> &nbsp; ${audit.jobId} &nbsp; ${job.timingMode||'timing unknown'} &nbsp; captions: ${job.captionMode||'off'}</p><div class="summary"><div class="metric"><b>${job.targetMinutes||'—'}m</b><span>TARGET</span></div><div class="metric"><b>${job.actualMinutes??'—'}</b><span>ACTUAL MINUTES</span></div><div class="metric"><b>${job.sceneCount??'—'}/${job.totalScenes??'—'}</b><span>SCENES</span></div><div class="metric"><b>${cost}</b><span>TOTAL COST</span></div><div class="metric"><b>${costPerMinute}</b><span>COST / MINUTE</span></div></div><div class="section"><h3>STAGE TIMING</h3><p class="muted">${escapeHtml(stage)} · first playable ${formatTime((job as any).firstPlayableMs)}</p></div><div class="section"><h3>PERSISTED ARTIFACTS</h3><table class="artifact-table"><thead><tr><th>Artifact</th><th>Bytes</th><th>State</th></tr></thead><tbody>${artifacts.map(([name,item])=>`<tr><td>${escapeHtml(name)}</td><td>${item.bytes??'—'}</td><td>${item.redacted?'<span class="badge warning">redacted</span>':item.present?'<span class="badge">present</span>':'missing'}</td></tr>`).join('')}</tbody></table></div><div class="section"><h3>SELECTED AUDIT JSON</h3><pre class="json">${escapeHtml(JSON.stringify({sourceFitness:audit.artifacts['source-fitness.json']?.value,intent:audit.artifacts['intent.json']?.value,teachingPlan:audit.artifacts['teaching-plan.json']?.value,timing:audit.artifacts['timings.json']?.value,exportTiming:audit.artifacts['export-timing.json']?.value,releaseAudit:audit.artifacts['final-release-audit.json']?.value,degradedStages:job.degradedStages},null,2))}</pre></div>`;}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));}
$('refresh').onclick=()=>void loadJobs();void loadJobs();
