/** Declarative model-facing schemas using semantic keys only.
 *
 *  Models emit these structures; runtime translates them into the internal
 *  TeachingPlanV2 / VisualSceneV2 / CompiledSceneV2 contracts that the rest of
 *  the pipeline already consumes. Translation types only — the identity
 *  authority is `harness/registry.ts`.
 */
import type { VisualArchetype, LayoutZone, MotionKind, ObjectState, CollisionPolicy, EasingKind } from '../types.js';
import type { SemanticKey } from './types.js';
import type { SemanticRelationRef } from './types.js';

/** High-level plan covering the whole lesson. */
export interface TeachingIntent {
  version: 2;
  lessonGoal: string;
  learnerAssumption?: string;
  centralQuestion?: string;
  requiredClaims: {
    id: string;
    statement: string;
    critical: boolean;
  }[];
  requiredMechanisms: {
    id: string;
    statement: string;
    critical: boolean;
    conceptKeys: SemanticKey[];
    requiresStateChange: boolean;
  }[];
  conceptRegistry: {
    key: SemanticKey;
    canonicalName: string;
    aliases: SemanticKey[];
    semanticType:
      | 'entity'
      | 'material'
      | 'process'
      | 'state'
      | 'quantity'
      | 'equation'
      | 'location'
      | 'role';
    visualFamily?: string;
    preferredColorRole?: string;
  }[];
  scenes: SceneTeachingIntent[];
}

/** One scene's worth of teaching intent. */
export interface SceneTeachingIntent {
  /** Stable semantic slug, e.g. "photosynthesis_inputs". Not a UUID. */
  key: string;
  centralConceptKey: SemanticKey;
  teachingGoal: string;
  learnerShouldUnderstand: string;
  mentalModel: string;
  beats: SemanticBeatV2[];
  requiredConceptKeys: SemanticKey[];
  requiredRelations: SemanticRelationRef[];
  candidateArchetypes: VisualArchetype[];
  continuity: {
    keepFromPrevious: SemanticKey[];
    prepareForNext: SemanticKey[];
    transitions?: {conceptKey: SemanticKey; action: 'KEEP'|'MOVE'|'TRANSFORM'|'REPLACE'|'REMOVE'|'REINTRODUCE'; fromState?: ObjectState; toState?: ObjectState; fromRepresentation?: string; toRepresentation?: string}[];
  };
}

/** A single beat expressed only with semantic keys. Model never owns beat IDs. */
export interface SemanticBeatV2 {
  /** Semantic slug, e.g. "beat_intro". */
  key: string;
  purpose: string;
  narrationDraft: string;
  requirementIds: string[];
  introduce: SemanticKey[];
  reinforce: SemanticKey[];
  transform: { conceptKey: SemanticKey; fromState: ObjectState; toState: ObjectState }[];
  relationFocus: string[];
  intentionalPause?: 'none' | 'short' | 'medium' | 'long';
}

/** A semantic object specification generated by the director. */
export interface SemanticObject {
  conceptKey: SemanticKey;
  /** Optional natural-language disambiguation when a concept appears more than once. */
  roleHint?: 'hero' | 'support' | 'before' | 'after' | 'equation' | 'annotation';
  label: string;
  role: 'hero' | 'support' | 'structure' | 'material' | 'equation' | 'annotation' | 'label' | 'decorative_support' | 'data';
  assetRef?: string;
  primitiveRef?: 'label' | 'rectangle' | 'circle' | 'equation';
  semanticPart?: string;
  state?: ObjectState;
  allowedStates?: ObjectState[];
  importance?: 'primary' | 'secondary' | 'tertiary';
  preferredZone?: LayoutZone;
  collisionPolicy?: CollisionPolicy;
}

/** A semantic beat action specification generated by the director. */
export interface SemanticAction {
  type: MotionKind;
  /** Concepts to act on. */
  conceptKeys: SemanticKey[];
  /** Relation references to animate: concept pair + relation type + optional targetPart. */
  relationRefs: SemanticRelationRef[];
  anchorText?: string;
  anchorOccurrence?: number;
  durationMs: number;
  leadMs: number;
  easing: EasingKind;
  fromState?: ObjectState;
  toState?: ObjectState;
  destination?: LayoutZone;
}

export interface SemanticResolvedBeat {
  /** Matches SceneTeachingIntent beat key. */
  key: string;
  narration: string;
  actions: SemanticAction[];
  intentionalPause?: 'none' | 'short' | 'medium' | 'long';
}
