import type {Plan,Scene} from './types.js';
import type {NodeKind} from './vocabulary.js';
type Label = string | [string, NodeKind] | [string, NodeKind, 'box'|'icon'|'illustration'|'circle'|'square'|'bullet'|'number'] | [string, NodeKind, 'annotation', string, ('below'|'above'|'left'|'right')?];
const fanOutFromRoot=['branch','hierarchy','radial'];
const scene=(id:string,title:string,narration:string,labels:Label[],layout:Scene['layout']='flow',note='')=>({id,title,narration,layout,note,
  nodes:labels.map((entry,i)=>{const [label,kind,shape,attachTo,position]=Array.isArray(entry)?entry:[entry,undefined,undefined,undefined,undefined];
    return {id:`n${i}`,label,wordIndex:Math.floor(i*narration.split(/\s+/).length/(labels.length+1)),...(kind?{kind}:{}),...(shape?{shape}:{}),...(shape==='annotation'?{attachTo,position:position||'below'}:{})};}),
  edges: fanOutFromRoot.includes(layout) ? labels.slice(1).map((_,i)=>({from:'n0',to:`n${i+1}`}))
    : layout==='convergence' ? labels.slice(0,-1).map((_,i)=>({from:`n${i}`,to:`n${labels.length-1}`}))
    : labels.slice(1).map((_,i)=>({from:`n${i}`,to:`n${i+1}`}))});
export const fixtures: Record<string, Plan>={
  attention:{version:1,title:'Attention, one idea at a time',scenes:[
    scene('context','Words need context','A word changes meaning with its surroundings. Consider the word bank. In one sentence it describes a financial institution. In another it describes the edge of a river. Attention lets a token gather information from the other tokens in its context.',['A token: bank','Nearby words','Contextual meaning'],'flow','The same token can need different information in different sentences.'),
    scene('qkv','Query, key, value','Each token representation is projected into a query, a key, and a value. The query represents what information this token seeks. Keys determine how compatible other tokens are with that query. Values carry the information that will be combined. These are learned vectors, not literal questions or labels.',[['Token representation','token'],['Query: what to seek','question'],['Key: compatibility','key'],['Value: information','container']],'branch','Q = XWq     K = XWk     V = XWv'),
    scene('weights','From compatibility to weights','Compare a query against every allowed key using dot products. Divide those scores by the square root of the key dimension. Apply any required mask, then softmax. The resulting nonnegative weights sum to one across the allowed positions. A causal mask blocks access to future tokens.',['Dot products','Scale and mask',['Softmax weights','graph']],'flow','Attention(Q, K, V) = softmax(QKᵀ / √dk + mask)V'),
    scene('combine','Blend information, preserve meaning','Use the attention weights to combine value vectors. For illustration, suppose three weights are zero point five, zero point four, and zero point one. Multiply each value by its weight and add the results. This produces the output for one query in one head. Multiple heads learn different projections.',['0.5 v₁ + 0.4 v₂ + 0.1 v₃','Weighted sum',['Output of one head','success']],'flow','Illustrative weights only. A full transformer also has projections, residual paths and feed-forward layers.')
  ]},
  photosynthesis:{version:1,title:'Photosynthesis, from light to sugar',scenes:[
    scene('inputs','What a plant needs','Plants use light energy to help build sugars from carbon dioxide and water. Leaves absorb light through pigments including chlorophyll. Roots provide water, and carbon dioxide enters the leaf through small pores called stomata. Oxygen is released as a product of the light reactions.',['Light energy','Water + carbon dioxide','Sugar + oxygen'],'flow','A simplified overview; the detailed chemistry occurs through several reactions.'),
    scene('light','Capture energy','In the thylakoid membranes of chloroplasts, light reactions convert captured light energy into chemical energy carriers. Water supplies electrons, and oxygen is released. The energy carriers ATP and NADPH support the next stage of sugar production.',['Light reactions','ATP and NADPH','Oxygen released'],'branch','Light reactions take place in thylakoid membranes.'),
    scene('carbon','Build carbon compounds','The Calvin cycle uses carbon dioxide and the products of the light reactions. Enzyme driven reactions produce a small carbon compound called G3P. Some of that material can contribute to sugars, while the rest helps regenerate the molecules needed to keep the cycle running.',['Carbon dioxide','Calvin cycle','G3P for sugars'],'flow','The Calvin cycle takes place in the stroma of the chloroplast.')
  ]},
  neuralnet:{version:1,title:'How a neural network learns',scenes:[
    scene('forward','A forward pass, step by step','Input features enter the network. Each layer multiplies its input by learned weights, adds a bias, and applies a nonlinear activation. The final layer produces a prediction, which is compared against the true label to compute a loss.',[['Input features','document'],['Hidden layer','model'],['Prediction','success'],['Loss','warning']],'timeline','Each step depends only on the step before it.'),
    scene('architecture','One layer, many connections','A layer is a group of units, each one a small model of its own. The output layer sits above every hidden layer, combining their signals into a single prediction. Depth lets the network build increasingly abstract features.',[['Output layer','model','illustration'],['Hidden units','token'],['Hidden units','token'],['Raw input','document']],'hierarchy','The output layer depends on every hidden unit beneath it.')
  ]},
  illustrations:{version:1,title:'Rich illustrations, not boxes',scenes:[
    scene('people','Teacher and student','A teacher explains a new idea. A student listens, and asks questions to check understanding. Learning happens through this exchange, not through a diagram alone.',[['A teacher explains','teacher','illustration'],['A student listens','student','illustration']],'compare','Two roles, drawn as full figures, not glyphs in a box.'),
    scene('system','An agent talks to a server','An autonomous agent sends a request to a server. The server consults a model to produce a response, and returns it to the agent.',[['An agent','agent','illustration'],['A server','server','illustration'],['A model','model','illustration']],'flow','Agent, server and model, each drawn stroke by stroke.')
  ]},
  icons:{version:1,title:'Icons with labels beside them',scenes:[
    scene('lookup','Icons paste beside their labels','A database stores records. A search finds the relevant record. A key unlocks access, and the cloud serves the result to a user. Each icon is pasted large with its explanation written beside it, not boxed.',[['Database stores','database','icon'],['Search finds','search','icon'],['Key unlocks','key','icon'],['Cloud serves','cloud','icon']],'flow','Four pasted icons, each explained by the text beside it.'),
  ]},
  shapes:{version:1,title:'Shapes beyond boxes',scenes:[
    scene('primitives','Circles squares badges bullets','A repeating cycle is round. A rigid screen is square. A number badge shows the count big. A bullet node lists takeaways plainly.',[['A repeating cycle','cycle','circle'],['A rigid screen','document','square'],['8 GPUs','server','number'],['Heat flows. Coils cool. Cycle repeats.','process','bullet']],'flow','Circle, square, number badge, bullet list — no rounded boxes.'),
    scene('forces','Opposites look opposite','Magnets pull together and push apart. Attraction draws two bodies inward. Repulsion drives them outward. The two forces use mirrored icons and opposite colors.',[['Attraction pulls inward','attract','icon'],['Repulsion pushes outward','repel','icon']],'compare','Mirrored glyphs, green versus red, for opposite forces.'),
    scene('annotated','Callouts explain beside boxes','A query asks what to seek. Keys offer compatibility scores. The blend weights each value. Boxes hold the concepts; short marginalia floats beside them.',[['Seeking query','question','icon'],['Key compatibility','key','icon'],['what am I looking for?','generic','annotation','n0','below'],['offered, not owned','generic','annotation','n1','right']],'flow','Annotations attach relatively; the compiler places them.'),
  ]},
  templates:{version:1,title:'Canonical domain compositions',scenes:[
    {...scene('handshake','The TLS handshake, message by message','A browser opens by sending a ClientHello. The server answers with its ServerHello and its certificate. The browser then sends its key exchange material, and both sides finish the handshake.',[['Web browser','browser','icon'],['Remote server','server','icon']],'flow','Two parties, four numbered messages — the ladder is the lesson.') ,template:'tls_handshake' as const},
    {...scene('equilibrium','Where price meets quantity','Demand falls as price rises, while supply grows with it. Where the two curves cross, the market clears: sellers sell exactly what buyers want at the equilibrium price.',[['Demand curve','graph'],['Supply curve','process']],'compare','The crossing point, not the boxes, is the lesson.') ,template:'supply_demand' as const},
  ]},
};
